#!/bin/bash

echo  "\n\n======= Setup NRS proxy.conf =======\n"
echo -n "1) Input your realm : "
read VAR_REALM1
echo -n "2) Input your IRS realm : "
read VAR_REALM2
echo -n "3) Input your TLR IP : "
read VAR_IP1
echo -n "4) Input your IRS IP : "
read VAR_IP2
echo -n "5) Input your secret key (e.g. 'eduroamkey') : "
read VAR_SECRET_KEY

sed 's/YOUR_REALM/'"$VAR_REALM1"'/' proxy.conf.temp > proxy_tmp1
sed 's/IRS_REALM/'"$VAR_REALM2"'/' proxy_tmp1 > proxy_tmp2
sed 's/TLR1_IP/'"$VAR_IP1"'/' proxy_tmp2 > proxy_tmp3
sed 's/IRS1_IP/'"$VAR_IP2"'/' proxy_tmp3 > proxy_tmp4
sed 's/EDUROAM_SECRET/'"$VAR_SECRET_KEY"'/' proxy_tmp4 > proxy.conf

rm -f proxy_tmp*

echo "\n\ndone!!!\n\n"




