#!/bin/bash

echo  "\n\n======= Setup IRS proxy.conf =======\n"
echo -n "1) Input your reaml : "
read VAR_REALM
echo -n "2) Input your NRS IP : "
read VAR_IP
echo -n "3) Input your secret key (e.g. 'eduroamkey') : "
read VAR_SECRET_KEY

sed 's/YOUR_REALM/'"$VAR_REALM"'/' proxy.conf.temp > proxy_tmp1
sed 's/FLR1_IP/'"$VAR_IP"'/' proxy_tmp1 > proxy_tmp2
sed 's/EDUROAM_SECRET/'"$VAR_SECRET_KEY"'/' proxy_tmp2 > proxy.conf

rm -f proxy_tmp*
cp -rf * /etc/freeradius
echo "\n\ndone!!!\n\n"




