#!/bin/bash

echo  "\n\n======= Setup IRS configuration =======\n"
echo -n "1) Input your reaml (e.g. 'test.rub.edu.bt) : "
read VAR_REALM
echo -n "2) Input your NRS IP : "
read VAR_IP
echo -n "3) Input your secret key (e.g. 'eduroamkey') : "
read VAR_SECRET_KEY
echo -n "4) Input your Country Domain (e.g. 'BT') : "
read VAR_COUNTRY_DOMAIN

#clients.conf setup
sed -e "s/YOUR_REALM/$VAR_REALM/" -e "s/FLR1_IP/$VAR_IP/" -e "s/EDUROAM_SECRET/$VAR_SECRET_KEY/" clients.conf.temp > clients.conf

#proxy.conf setup
sed -e "s/YOUR_REALM/$VAR_REALM/" -e "s/FLR1_IP/$VAR_IP/" -e "s/EDUROAM_SECRET/$VAR_SECRET_KEY/" proxy.conf.temp > proxy.conf

#f_ticks setup
sed 's/YOUR_COUNTRY/'"$VAR_COUNTRY_DOMAIN"'/' f_ticks.temp > ./mods-available/f_ticks

#eapol setup
cp /home/xeap/xeap-freeradius3/eapol_test/eapol_test /usr/local/bin
chmod 755 /usr/local/bin/eapol_test

cp -rf * /etc/freeradius

#simbolic setup
ln -s -f /etc/freeradius/sites-available/eduroam /etc/freeradius/sites-enabled/eduroam
ln -s -f /etc/freeradius/mods-available/f_ticks /etc/freeradius/mods-enabled/f_ticks

echo "\n\ndone!!!\n\n"




